### PR TITLE
Fix invalid routing config on Symfony < 4.1

### PR DESCRIPTION
**Pull request by ostrolucky**
Fixes https://github.com/prestaconcept/PrestaSitemapBundle/issues/221. Was regression from https://github.com/prestaconcept/PrestaSitemapBundle/pull/213

### CODE REVIEW

**Comment by yann-eugone** [comment]
Thank you for addind this fix, I feel pretty inconfortable with this issue because we didn't see it before.

Can you imagine a test that did avoid this ?

**Comment by ostrolucky** [comment]
> Can you imagine a test that did avoid this ?

What do you mean?

**Comment by yann-eugone** [comment]
I mean, that issue was not spotted by our test suite.

The usual process is to write a test that fails with the old code source, fix the code so the test pass.

**Comment by ostrolucky** [comment]
I mean no test case was touched in https://github.com/prestaconcept/PrestaSitemapBundle/pull/213 where regression was introduced either. It was also very poor on details. Normally I would adjust tests, but this is not my project and it lacks proper integration tests. Quite contrary, `SitemapControllerTest` goes out of its way to avoid using routing. Routing file for testing was also overriddden for unknown reason. If I was maintainer of this project, I would replace these tests with tests using official practice, by using symfony webtest browser and also remove overridden routes, but I am not so I'm not comfortable outright doing such changes.

**Comment by yann-eugone** [comment]
Fine, I will do my best to test this over all symfony versions we support before merging, releasing it.

I known this package has some troubles, specially with tests. Will do my best to rewrite the test suite some day.

**Comment by ostrolucky** [comment]
Let me know if you need some help. Biggest worry of contributors is that changes are rejected, but if you can guide me what you intend to do, I might help.

**Comment by yann-eugone** [comment]
We will have to merge it if not working on 3.4, but I have to be certain that other versions will not break on the same time. As tests are not helpful (for now) I will have to test it myself, but Monday 😉

**Comment by yann-eugone** [comment]
Did you tested that code against any 4.x version ? On my side I have an other issue with on symfony > 4.0 : 

```
Controller "Presta\SitemapBundle\Controller\SitemapController" cannot be fetched from the container because it is private.
Did you forget to tag the service with "controller.service_arguments"?
```

Caused by 

```
Too few arguments to function Presta\SitemapBundle\Controller\SitemapController::__construct(), 
0 passed in /src/vendor/symfony/http-kernel/Controller/ControllerResolver.php on line 133 
and exactly 2 expected
```

This is because the route is now bound to the `Presta\SitemapBundle\Controller\SitemapController` service id, which is private.

Adding `public="true"` to the alias you introduced solved the issue on my side.

Also, I created #223 with some tests that should prove that this issue will not appear again.

**Comment by ostrolucky** [comment]
Nope, I didn't test it on 4.0, so that error is indeed possible

**Comment by yann-eugone** [comment]
I about to merge this PR, then rebase #223 to see if added tests actually pass with these changes
